import type { Metadata } from "next";
import "./globals.css";
import PrimaryNavigation from "@/components/navigation/PrimaryNavigation";
import Copyright from "@/components/footer/Copyright";
import { getServerSession } from "next-auth";
import { authOptions } from "./api/auth/[...nextauth]/route";
import SessionProvider from "@/context/AuthContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  const session = await getServerSession(authOptions);
  // console.log("session", session);
  


  return (
    <html lang="en">
      <body className="bg-slate-100">
        <SessionProvider>
          {/* header */}
          <div className="bg-slate-600">
            <PrimaryNavigation />
          </div>
          {/* body */}
          <div>
            <main className="max-w-screen-2xl px-5 xl:px-10 mx-auto py-[10vh]">{children}</main>
          </div>



          {/* footer */}
          <Copyright />
        </SessionProvider>
      </body>
    </html>
  );
}
